# Resolve one link item to pkg-config flags. A target built here installs into ${libdir}
# and needs no -L of its own.
function(finufft_pc_item item out_flags)
    set(flags ${${out_flags}})
    if(TARGET ${item})
        get_target_property(imported ${item} IMPORTED)
        if(NOT imported)
            get_target_property(name ${item} OUTPUT_NAME)
            if(NOT name)
                set(name ${item})
            endif()
            list(APPEND flags "-l${name}")
        else()
            get_target_property(loc ${item} IMPORTED_LOCATION)
            if(NOT loc)
                get_target_property(configs ${item} IMPORTED_CONFIGURATIONS)
                if(configs)
                    list(GET configs 0 first)
                    get_target_property(loc ${item} IMPORTED_LOCATION_${first})
                endif()
            endif()
            if(loc)
                finufft_pc_item("${loc}" flags)
            else()
                # An INTERFACE IMPORTED target, which is what FindFFTW creates: the
                # library sits in the link interface, not in a location property.
                get_target_property(deps ${item} INTERFACE_LINK_LIBRARIES)
                foreach(dep ${deps})
                    finufft_pc_item("${dep}" flags)
                endforeach()
            endif()
        endif()
    elseif(item MATCHES "^-")
        list(APPEND flags "${item}")
    elseif(IS_ABSOLUTE "${item}")
        get_filename_component(dir "${item}" DIRECTORY)
        get_filename_component(name "${item}" NAME_WE)
        string(REGEX REPLACE "^lib" "" name "${name}")
        list(APPEND flags "-L${dir}" "-l${name}")
    elseif(item MATCHES "\\$<" OR item MATCHES "::")
        # A generator expression, or a target this directory cannot see: neither has a
        # name a linker could use.
        message(WARNING "finufft.pc cannot name the link item ${item}")
    else()
        # A bare library name, which is what -DFINUFFT_FFTW_LIBRARIES=fftw3;fftw3f gives.
        list(APPEND flags "-l${item}")
    endif()
    set(${out_flags} ${flags} PARENT_SCOPE)
endfunction()

# The FFT backend's imported targets are created in src/, so they exist only in that
# directory's scope. Resolve them to flags there and hand the result up.
function(finufft_pc_fft_flags out)
    set(flags "")
    if(TARGET finufft_fftlibs)
        get_target_property(fftlibs finufft_fftlibs INTERFACE_LINK_LIBRARIES)
        foreach(item ${fftlibs})
            finufft_pc_item(${item} flags)
        endforeach()
    endif()
    set(${out} "${flags}" PARENT_SCOPE)
endfunction()

# A shared libfinufft carries its dependencies itself, so Libs.private stays empty.
# A static one needs everything the archive does not contain: the FFT backend, the
# OpenMP runtime, and the C++ runtime a C or Fortran consumer does not link by itself.
function(finufft_pc_libs_private out)
    set(flags "")
    if(NOT FINUFFT_STATIC_LINKING)
        set(${out} "" PARENT_SCOPE)
        return()
    endif()
    if(TARGET finufft_common)
        finufft_pc_item(finufft_common flags)
    endif()
    list(APPEND flags ${FINUFFT_PC_FFT_FLAGS})
    if(FINUFFT_USE_OPENMP AND TARGET OpenMP::OpenMP_CXX)
        # -fopenmp is a link flag for GCC and for clang that takes it directly. Apple clang
        # reaches OpenMP only through -Xclang/-Xpreprocessor and needs the runtime named.
        if(OpenMP_CXX_FLAGS MATCHES "-X(clang|preprocessor)")
            foreach(lib ${OpenMP_CXX_LIBRARIES})
                finufft_pc_item("${lib}" flags)
            endforeach()
        else()
            list(APPEND flags ${OpenMP_CXX_FLAGS})
        endif()
    elseif(CMAKE_THREAD_LIBS_INIT)
        # DUCC0 links Threads::Threads privately when OpenMP is off
        list(APPEND flags ${CMAKE_THREAD_LIBS_INIT})
    endif()
    foreach(runtime ${CMAKE_CXX_IMPLICIT_LINK_LIBRARIES})
        if(runtime STREQUAL "stdc++" OR runtime STREQUAL "c++")
            list(APPEND flags "-l${runtime}")
        endif()
    endforeach()
    list(APPEND flags "-lm")
    list(REMOVE_DUPLICATES flags)
    list(JOIN flags " " joined)
    set(${out} "${joined}" PARENT_SCOPE)
endfunction()

function(finufft_write_pkgconfig)
    # Derive the prefix from where the .pc file itself ends up, so `cmake --install
    # --prefix` and a relocated install tree still resolve. An absolute libdir pins the
    # file outside the prefix, so there is no relative path to walk and the prefix is
    # whatever the configure step said.
    if(IS_ABSOLUTE "${CMAKE_INSTALL_LIBDIR}")
        set(FINUFFT_PC_PREFIX "${CMAKE_INSTALL_PREFIX}")
        set(FINUFFT_PC_LIBDIR "${CMAKE_INSTALL_LIBDIR}")
    else()
        file(RELATIVE_PATH rel "${CMAKE_INSTALL_FULL_LIBDIR}/pkgconfig" "${CMAKE_INSTALL_PREFIX}")
        if(rel STREQUAL "")
            set(rel ".")
        endif()
        set(FINUFFT_PC_PREFIX "\${pcfiledir}/${rel}")
        set(FINUFFT_PC_LIBDIR "\${prefix}/${CMAKE_INSTALL_LIBDIR}")
    endif()
    if(IS_ABSOLUTE "${CMAKE_INSTALL_INCLUDEDIR}")
        set(FINUFFT_PC_INCLUDEDIR "${CMAKE_INSTALL_INCLUDEDIR}")
    else()
        set(FINUFFT_PC_INCLUDEDIR "\${prefix}/${CMAKE_INSTALL_INCLUDEDIR}")
    endif()
    finufft_pc_libs_private(FINUFFT_PC_LIBS_PRIVATE)
    configure_file(${PROJECT_SOURCE_DIR}/cmake/finufft.pc.in ${CMAKE_CURRENT_BINARY_DIR}/finufft.pc @ONLY)
endfunction()
