name: Build MATLAB MEX

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: windows-2022
          - os: macos-13
          - os: macos-14
          - os: macos-15
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup C++ toolchain
        uses: aminya/setup-cpp@v1.7.1
        with:
          cmake: true
          ninja: true
          vcvarsall: true

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b
          products: MATLAB
          cache: true

      # macOS: keep OpenMP ON, but do NOT preload Homebrew's libomp.
      # We rely on MATLAB's libiomp5.dylib via use_matlab_openmp().
      - name: Set macOS deployment target
        if: runner.os == 'macOS'
        shell: bash
        run: |
          ver="${{ matrix.os }}"; ver="${ver#macos-}"
          echo "MACOSX_DEPLOYMENT_TARGET=${ver}.0" >> "$GITHUB_ENV"

      - name: Configure & Build
        shell: bash
        run: |
          # Ensure MATLAB is on PATH if provided by setup-matlab
          if [ -n "${MATLAB_ROOT:-}" ]; then export PATH="${MATLAB_ROOT}/bin:${PATH}"; fi
          cmake -S . -B build -G Ninja \
            -DFINUFFT_USE_DUCC0=ON \
            -DFINUFFT_USE_OPENMP=ON \
            -DFINUFFT_MATLAB_INSTALL=ON
          cmake --build build --target finufft_mex --parallel

      - name: Run fullmathtest.m
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath(genpath('matlab'));
            addpath(genpath('build'));
            fullmathtest

      - name: Package with CPack
        shell: bash
        run: cmake --build build --target package

      - uses: actions/upload-artifact@v4
        with:
          name: finufft-matlab-mex-${{ matrix.os }}
          path: |
            build/*.zip
            build/*.tar.gz
          if-no-files-found: error
