name: Build MATLAB MEX

on: [push, pull_request]

jobs:
  matlab-mex:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
          - os: windows-latest
          - os: macos-14
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup C++ toolchain
        uses: aminya/setup-cpp@v1.7.1
        with:
          cmake: true
          ninja: true
          vcvarsall: true
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b
          products: MATLAB
          cache: true
      - name: Install libomp (macOS) and set env
        if: runner.os == 'macOS'
        shell: bash
        run: |
          export HOMEBREW_NO_ANALYTICS=1 HOMEBREW_NO_INSTALL_CLEANUP=1
          brew install libomp
          {
            echo "LDFLAGS=-L$(brew --prefix libomp)/lib"
            echo "CPPFLAGS=-I$(brew --prefix libomp)/include"
            echo "LIBRARY_PATH=$(brew --prefix libomp)/lib"
            echo "DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib"
            echo "CMAKE_PREFIX_PATH=$(brew --prefix libomp)"
            echo "MAC_TARGETS=12.0 13.0"
          } >> "$GITHUB_ENV"
      # ---------- Linux & Windows ----------
      - name: Configure & Build (Linux/Windows, DUCC0)
        if: runner.os != 'macOS'
        shell: bash
        run: |
          cmake -S . -B build -G Ninja \
            -DFINUFFT_USE_CPU=ON \
            -DFINUFFT_USE_DUCC0=ON \
            -DFINUFFT_MATLAB_INSTALL=ON
          cmake --build build --target finufft_mex --parallel
      - name: Run fullmathtest.m (Linux/Windows)
        if: runner.os != 'macOS'
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath(genpath('matlab'));
            addpath(genpath('build'));  % contains MEX + .m files after post-build copy
            fullmathtest
      # Package via CPack (archives contain only top-level "matlab/")
      - name: Package (Linux/Windows) with CPack
        if: runner.os != 'macOS'
        shell: bash
        run: |
          cmake --build build --target package
          echo "Produced packages:"
          ls -l build/*.zip build/*.tar.gz 2>/dev/null || true

      - name: Configure & Build (macOS; DUCC0, multi-target)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          for tgt in ${MAC_TARGETS}; do
            bdir="build_mac_${tgt}"
            cmake -S . -B "${bdir}" -G Ninja \
              -DFINUFFT_USE_CPU=ON \
              -DFINUFFT_USE_DUCC0=ON \
              -DFINUFFT_MATLAB_INSTALL=ON \
              -DCMAKE_OSX_DEPLOYMENT_TARGET="${tgt}"
            cmake --build "${bdir}" --target finufft_mex --parallel
          done

      - name: Run fullmathtest.m (macOS per target)
        if: runner.os == 'macOS'
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath(genpath('matlab'));
            targets = regexp(getenv('MAC_TARGETS'), '\s+', 'split');
            for i = 1:numel(targets)
              tgt = strtrim(targets{i});
              p = genpath(fullfile('build_mac_', tgt));
              addpath(p);
              fullmathtest;
            end
            clear targets tgt p i;
      - name: Package (macOS) with CPack (per target)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          for tgt in ${MAC_TARGETS}; do
            cmake --build "build_mac_${tgt}" --target package
          done
          echo "Produced packages:"
          ls -l build_mac_*/finufft-matlab-mex-macos-*.tar.gz || true

      - uses: actions/upload-artifact@v4
        with:
          name: finufft-matlab-mex-${{ matrix.os }}
          path: |
            build/*.zip
            build/*.tar.gz
            build_mac_*/finufft-matlab-mex-macos-*.tar.gz
          if-no-files-found: error
