name: Build MATLAB MEX

on: [push, pull_request]

jobs:
  matlab-mex:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux: GCC 11 (ABI compatible with MATLAB R2023b libstdc++)
          - os: ubuntu-22.04
            compiler: gcc
            compiler_version: '11'
            cc: gcc-11
            cxx: g++-11
          # Windows: MSVC (setup-cpp will set vcvarsall)
          - os: windows-latest
            compiler: msvc
            compiler_version: ''
            cc: cl
            cxx: cl
          # macOS 14: LLVM/Clang
          - os: macos-14
            compiler: llvm
            compiler_version: ''
            cc: clang
            cxx: clang++

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      # Toolchain: CMake + Ninja (+ MSVC env on Windows)
      - name: Setup C++ toolchain
        uses: aminya/setup-cpp@v1.7.1
        with:
          compiler: ${{ matrix.compiler }}        # gcc / msvc / llvm
          version: ${{ matrix.compiler_version }} # '11' for gcc, empty otherwise
          cmake: true
          ninja: true
          vcvarsall: ${{ matrix.compiler == 'msvc' }}

      # Linux: ensure gcc-11/g++-11 are present (avoid "g++-11: not found")
      - name: Install GCC 11 (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-11 g++-11

      # MATLAB for find_package(Matlab) and tests
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: R2023b
          products: MATLAB
          cache: true

      # macOS: OpenMP runtime + multi-target matrix
      - name: Install libomp (macOS) and set env
        if: runner.os == 'macOS'
        shell: bash
        run: |
          set -euo pipefail
          export HOMEBREW_NO_ANALYTICS=1 HOMEBREW_NO_INSTALL_CLEANUP=1
          brew install libomp
          {
            echo "LDFLAGS=-L$(brew --prefix libomp)/lib"
            echo "CPPFLAGS=-I$(brew --prefix libomp)/include"
            echo "LIBRARY_PATH=$(brew --prefix libomp)/lib"
            echo "DYLD_LIBRARY_PATH=$(brew --prefix libomp)/lib"
            echo "CMAKE_PREFIX_PATH=$(brew --prefix libomp)"
            echo "MAC_TARGETS=12.0 13.0"
          } >> "$GITHUB_ENV"

      # ---------- Linux & Windows ----------
      - name: Configure & Build (Linux/Windows, DUCC0)
        if: runner.os != 'macOS'
        shell: bash
        run: |
          set -euo pipefail
          EXTRA_FLAGS=""
          if [ "$RUNNER_OS" != "Windows" ]; then
            EXTRA_FLAGS="-DCMAKE_C_COMPILER=${{ matrix.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}"
          fi
          cmake -S . -B build -G Ninja \
            -DFINUFFT_USE_CPU=ON \
            -DFINUFFT_USE_DUCC0=ON \
            -DFINUFFT_MATLAB_INSTALL=ON \
            ${EXTRA_FLAGS}
          cmake --build build --target finufft_mex --parallel

      # Tests: favor MATLAB's libstdc++ at runtime (Linux only)
      - name: Run fullmathtest.m (Linux/Windows)
        if: runner.os != 'macOS'
        uses: matlab-actions/run-command@v2
        env:
          # Prepend MATLAB's sys/os/glnxa64 so its libstdc++.so.6 is chosen.
          LD_LIBRARY_PATH: ${{ runner.os == 'Linux' && format('{0}/MATLAB/2023.2.999/x64/sys/os/glnxa64:{1}', env.RUNNER_TOOL_CACHE, env.LD_LIBRARY_PATH) || env.LD_LIBRARY_PATH }}
        with:
          command: |
            addpath(genpath('matlab'));
            addpath(genpath('build'));  % contains MEX + .m files after post-build copy
            fullmathtest

      # Package via CPack (archives contain only top-level "matlab/")
      - name: Package (Linux/Windows) with CPack
        if: runner.os != 'macOS'
        shell: bash
        run: |
          set -euo pipefail
          cmake --build build --target package
          echo "Produced packages:"
          ls -l build/*.zip build/*.tar.gz 2>/dev/null || true

      # ---------- macOS (per deployment target) ----------
      - name: Configure & Build (macOS; DUCC0, multi-target)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          set -euo pipefail
          for tgt in ${MAC_TARGETS}; do
            bdir="build_mac_${tgt}"
            cmake -S . -B "${bdir}" -G Ninja \
              -DFINUFFT_USE_CPU=ON \
              -DFINUFFT_USE_DUCC0=ON \
              -DFINUFFT_MATLAB_INSTALL=ON \
              -DCMAKE_OSX_DEPLOYMENT_TARGET="${tgt}" \
              -DCMAKE_C_COMPILER=${{ matrix.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.cxx }}
            cmake --build "${bdir}" --target finufft_mex --parallel
          done

      - name: Run fullmathtest.m (macOS per target)
        if: runner.os == 'macOS'
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath(genpath('matlab'));
            targets = regexp(getenv('MAC_TARGETS'), '\s+', 'split');
            for i = 1:numel(targets)
              tgt = strtrim(targets{i});
              p = genpath(fullfile('build_mac_', tgt));
              addpath(p);
              fullmathtest;
              rmpath(p);
            end
            clear targets tgt p i;

      - name: Package (macOS) with CPack (per target)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          set -euo pipefail
          for tgt in ${MAC_TARGETS}; do
            cmake --build "build_mac_${tgt}" --target package
          done
          echo "Produced packages:"
          ls -l build_mac_*/finufft-matlab-mex-macos-*.tar.gz || true

      # Upload only CPack-produced archives (clean)
      - uses: actions/upload-artifact@v4
        with:
          name: finufft-matlab-mex-${{ matrix.os }}
          path: |
            build/*.zip
            build/*.tar.gz
            build_mac_*/finufft-matlab-mex-macos-*.tar.gz
          if-no-files-found: error
