name: Python Wheel Build

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  Linux:
    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_x86_64:latest

    steps:
    - uses: actions/checkout@v2

    - name: Install fftw
      run: |
        yum install -y fftw3-devel

    - name: Install ffi
      run: |
        yum install -y libffi-devel

    - name: Compile python bindings
      run: |
        python/ci/build-wheels-linux.sh

    - name: Upload wheels
      uses: actions/upload-artifact@v2
      with:
        name: linux-wheels
        path: python/wheelhouse/finufft*manylinux*.whl
