name: Build and Test FINUFFT on Red Hat UBI

on: [ push, pull_request ]

jobs:
  build-matrix:
    name: ${{ matrix.build_type }} on ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Use UBI 7, 8, and 9 images from the free registry.access.redhat.com
        image:
          - registry.access.redhat.com/ubi7/ubi:latest
          - registry.access.redhat.com/ubi8/ubi:latest
          - registry.access.redhat.com/ubi9/ubi:latest
        build_type:
          - Release
    container:
      image: ${{ matrix.image }}

    steps:
      - name: Install development tools
        run: |
          # UBI 7 uses yum, UBI 8/9 use dnf
          if grep -q 'VERSION_ID="7' /etc/os-release; then
            yum install -y epel-release centos-release-scl devtoolset-9 cmake3 fftw-devel git make
            source scl_source enable devtoolset-9
            echo CMAKE=cmake3 >> $GITHUB_ENV
          else
            dnf install -y gcc gcc-c++ cmake fftw-devel git make
            echo CMAKE=cmake >> $GITHUB_ENV
          fi

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Configure (C++17, FFTW, OpenMP)
        run: |
          $CMAKE -S . -B build -DCMAKE_BUILD_TYPE=Release -DFINUFFT_BUILD_TESTS=ON

      - name: Build
        run: |
          cmake --build ./build --config Release

      - name: Test
        working-directory: ./build
        run: |
          ctest -C Release --output-on-failure
