# this test build the app using cmake and tests it with ctest
name: CMake Windows Clang

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_PRESET: default

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - { name: "Windows clang", os: windows-latest, cc: "clang", cxx: "clang++" }        
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ninja
        uses: ashutoshvarma/setup-ninja@master
        with:
          # ninja version to download. Default: 1.10.0
          version: 1.10.0

      - name: Setup Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64

      - name: Build with CMake
        uses: ashutoshvarma/action-cmake-build@master
        with:
          build-dir: ${{ runner.workspace }}/build
          cc: ${{ matrix.config.cc }}
          cxx: ${{ matrix.config.cxx }}
          configure-options: -G Ninja -DFINUFFT_BUILD_TESTS=ON -DFINUFFT_STATIC_LINKING=OFF
          build-type: Release
          run-test: true
          ctest-options: --test-dir test  --output-on-failure 
          parallel: 14
          build-options: --verbose
